/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    /** Health */
    get: operations["health_api_health_get"];
  };
  "/api/requirements": {
    /**
     * List Requirements
     * @description List all requirements in the workspace.
     */
    get: operations["list_requirements_api_requirements_get"];
    /**
     * Create Requirement
     * @description Create a new requirement.
     */
    post: operations["create_requirement_api_requirements_post"];
  };
  "/api/requirements/{req_id}": {
    /**
     * Get Requirement
     * @description Get a specific requirement by ID.
     */
    get: operations["get_requirement_api_requirements__req_id__get"];
  };
  "/api/requirements/{req_id}/transition": {
    /**
     * Transition Requirement Status
     * @description Transition a requirement to a new status.
     */
    post: operations["transition_requirement_status_api_requirements__req_id__transition_post"];
  };
  "/api/requirements/{req_id}/delivery-summary": {
    /**
     * Get Requirement Delivery Summary
     * @description Get aggregated delivery progress for a requirement.
     */
    get: operations["get_requirement_delivery_summary_api_requirements__req_id__delivery_summary_get"];
  };
  "/api/design-docs": {
    /**
     * List Design Docs
     * @description List all design docs in the workspace.
     */
    get: operations["list_design_docs_api_design_docs_get"];
  };
  "/api/design-docs/{design_id}": {
    /**
     * Get Design Doc
     * @description Get a specific design doc by ID.
     */
    get: operations["get_design_doc_api_design_docs__design_id__get"];
    /**
     * Update Design Doc
     * @description Update a design doc.
     */
    patch: operations["update_design_doc_api_design_docs__design_id__patch"];
  };
  "/api/design-docs/{design_id}/approve": {
    /**
     * Approve Design
     * @description Approve a design doc and transition the linked requirement.
     */
    post: operations["approve_design_api_design_docs__design_id__approve_post"];
  };
  "/api/design-docs/{design_id}/send-back": {
    /**
     * Send Back Design
     * @description Send back a design doc for revision.
     */
    post: operations["send_back_design_api_design_docs__design_id__send_back_post"];
  };
  "/api/balance-tables": {
    /**
     * List Balance Tables
     * @description List all balance tables.
     */
    get: operations["list_balance_tables_api_balance_tables_get"];
    /**
     * Create Balance Table
     * @description Create a new balance table.
     */
    post: operations["create_balance_table_api_balance_tables_post"];
  };
  "/api/balance-tables/{table_id}": {
    /**
     * Get Balance Table
     * @description Get a specific balance table.
     */
    get: operations["get_balance_table_api_balance_tables__table_id__get"];
    /**
     * Update Balance Table
     * @description Update a balance table.
     */
    patch: operations["update_balance_table_api_balance_tables__table_id__patch"];
  };
  "/api/bugs": {
    /**
     * List Bugs
     * @description List all bugs in the workspace.
     */
    get: operations["list_bugs_api_bugs_get"];
    /**
     * Create Bug
     * @description Create a new bug.
     */
    post: operations["create_bug_api_bugs_post"];
  };
  "/api/bugs/{bug_id}": {
    /**
     * Get Bug
     * @description Get a specific bug by ID.
     */
    get: operations["get_bug_api_bugs__bug_id__get"];
  };
  "/api/bugs/{bug_id}/transition": {
    /**
     * Transition Bug Status
     * @description Transition a bug to a new status.
     */
    post: operations["transition_bug_status_api_bugs__bug_id__transition_post"];
  };
  "/api/logs": {
    /**
     * List Logs
     * @description List action logs, most recent first.
     */
    get: operations["list_logs_api_logs_get"];
  };
  "/api/workflows/run-design": {
    /**
     * Run Design Workflow
     * @description Run the design workflow for a requirement.
     */
    post: operations["run_design_workflow_api_workflows_run_design_post"];
  };
  "/api/workflows/run-dev": {
    /**
     * Run Dev Workflow
     * @description Run the dev workflow for a requirement.
     */
    post: operations["run_dev_workflow_api_workflows_run_dev_post"];
  };
  "/api/workflows/run-qa": {
    /**
     * Run Qa Workflow
     * @description Run the QA workflow for a requirement.
     */
    post: operations["run_qa_workflow_api_workflows_run_qa_post"];
  };
  "/api/pool/status": {
    /**
     * Get Pool Status
     * @description Return current agent thread pool status.
     */
    get: operations["get_pool_status_api_pool_status_get"];
  };
  "/api/meetings": {
    /** List Meetings */
    get: operations["list_meetings_api_meetings_get"];
  };
  "/api/meetings/{meeting_id}": {
    /** Get Meeting */
    get: operations["get_meeting_api_meetings__meeting_id__get"];
  };
  "/api/meetings/{meeting_id}/transcript": {
    /** Get Meeting Transcript */
    get: operations["get_meeting_transcript_api_meetings__meeting_id__transcript_get"];
  };
  "/api/meetings/{meeting_id}/delivery-plan": {
    /**
     * Generate Delivery Plan
     * @description Generate a delivery plan from a completed meeting.
     */
    post: operations["generate_delivery_plan_api_meetings__meeting_id__delivery_plan_post"];
  };
  "/api/delivery-board": {
    /**
     * List Delivery Board
     * @description List all delivery board items (plans, tasks, decision gates).
     */
    get: operations["list_delivery_board_api_delivery_board_get"];
  };
  "/api/kickoff-decision-gates/{gate_id}/resolve": {
    /**
     * Resolve Decision Gate
     * @description Resolve a kickoff decision gate.
     */
    post: operations["resolve_decision_gate_api_kickoff_decision_gates__gate_id__resolve_post"];
  };
  "/api/delivery-tasks/{task_id}/start": {
    /**
     * Start Delivery Task
     * @description Start a delivery task.
     */
    post: operations["start_delivery_task_api_delivery_tasks__task_id__start_post"];
  };
  "/api/delivery-tasks/{task_id}/retry": {
    /**
     * Retry Delivery Task
     * @description Reset a failed delivery task so the delivery runner can execute it again.
     */
    post: operations["retry_delivery_task_api_delivery_tasks__task_id__retry_post"];
  };
  "/api/delivery-tasks/{task_id}/complete": {
    /**
     * Complete Delivery Task
     * @description Complete a delivery task, persisting execution results and releasing the lease.
     */
    post: operations["complete_delivery_task_api_delivery_tasks__task_id__complete_post"];
  };
  "/api/delivery-tasks/{task_id}/events": {
    /**
     * Get Delivery Task Events
     * @description Return chronological task events for a delivery task.
     */
    get: operations["get_delivery_task_events_api_delivery_tasks__task_id__events_get"];
  };
  "/api/delivery-tasks/{task_id}/session": {
    /**
     * Get Delivery Task Session
     * @description Return Claude session messages attached to a delivery task.
     */
    get: operations["get_delivery_task_session_api_delivery_tasks__task_id__session_get"];
  };
  "/api/clarifications/requirements/{req_id}/session": {
    /** Get Session State */
    get: operations["get_session_state_api_clarifications_requirements__req_id__session_get"];
    /** Start Or Get Session */
    post: operations["start_or_get_session_api_clarifications_requirements__req_id__session_post"];
  };
  "/api/clarifications/requirements/{req_id}/messages": {
    /** Send Message */
    post: operations["send_message_api_clarifications_requirements__req_id__messages_post"];
  };
  "/api/clarifications/requirements/{req_id}/kickoff": {
    /** Start Kickoff */
    post: operations["start_kickoff_api_clarifications_requirements__req_id__kickoff_post"];
  };
  "/api/clarifications/kickoff-tasks/{task_id}": {
    /** Get Kickoff Task */
    get: operations["get_kickoff_task_api_clarifications_kickoff_tasks__task_id__get"];
  };
  "/api/sessions/project/{project_id}": {
    /**
     * List Sessions
     * @description List all agent sessions for a project.
     */
    get: operations["list_sessions_api_sessions_project__project_id__get"];
  };
  "/api/sessions": {
    /**
     * List All Sessions
     * @description List all agent sessions across projects.
     */
    get: operations["list_all_sessions_api_sessions_get"];
  };
  "/api/sessions/{session_composite_id}/status": {
    /**
     * Get Session Status
     * @description Get session status including whether the agent is busy (lease held).
     */
    get: operations["get_session_status_api_sessions__session_composite_id__status_get"];
  };
  "/api/agents/{project_id}/{agent}/chat": {
    /**
     * Chat With Agent
     * @description Send a message to an idle agent and get a response.
     */
    post: operations["chat_with_agent_api_agents__project_id___agent__chat_post"];
  };
  "/api/agents/{project_id}/{agent}/messages": {
    /**
     * Get Agent Messages
     * @description Load chat history for an agent session from the Claude CLI transcript.
     */
    get: operations["get_agent_messages_api_agents__project_id___agent__messages_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** ActionLog */
    ActionLog: {
      /** Id */
      id: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Actor */
      actor: string;
      /** Action */
      action: string;
      /** Target Type */
      target_type: string;
      /** Target Id */
      target_id: string;
      /** Message */
      message: string;
      /** Metadata */
      metadata?: {
        [key: string]: components["schemas"]["JsonValue"];
      };
    };
    /** AgentOpinion */
    AgentOpinion: {
      /** Agent Role */
      agent_role: string;
      /** Summary */
      summary: string;
      /** Proposals */
      proposals?: string[];
      /** Risks */
      risks?: string[];
      /** Open Questions */
      open_questions?: string[];
    };
    /** BalanceTable */
    BalanceTable: {
      /** Id */
      id: string;
      /** Requirement Id */
      requirement_id: string;
      /** Table Name */
      table_name: string;
      /** Columns */
      columns?: string[];
      /** Rows */
      rows?: components["schemas"]["BalanceTableRow"][];
      /** Locked Cells */
      locked_cells?: string[];
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status?: "draft" | "pending_user_review" | "approved" | "sent_back";
    };
    /** BalanceTableRow */
    BalanceTableRow: {
      /** Values */
      values: {
        [key: string]: string | number | boolean;
      };
    };
    /**
     * BalanceTableUpdate
     * @description Request model for updating a balance table.
     */
    BalanceTableUpdate: {
      /** Rows */
      rows?: {
          [key: string]: unknown;
        }[] | null;
      /** Locked Cells */
      locked_cells?: string[] | null;
    };
    /** Body_send_back_design_api_design_docs__design_id__send_back_post */
    Body_send_back_design_api_design_docs__design_id__send_back_post: {
      /** Reason */
      reason: string;
    };
    /** Body_update_design_doc_api_design_docs__design_id__patch */
    Body_update_design_doc_api_design_docs__design_id__patch: {
      /** Title */
      title?: string | null;
      /** Summary */
      summary?: string | null;
      /** Core Rules */
      core_rules?: string[] | null;
      /** Acceptance Criteria */
      acceptance_criteria?: string[] | null;
      /** Open Questions */
      open_questions?: string[] | null;
    };
    /** BugCard */
    BugCard: {
      /** Id */
      id: string;
      /** Requirement Id */
      requirement_id: string;
      /** Title */
      title: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "low" | "medium" | "high" | "critical";
      /**
       * Status
       * @default new
       * @enum {string}
       */
      status?: "new" | "fixing" | "fixed" | "verifying" | "closed" | "reopened" | "needs_user_decision";
      /**
       * Reopen Count
       * @default 0
       */
      reopen_count?: number;
      /** Owner */
      owner: string;
      /** Repro Steps */
      repro_steps?: string[];
      /** Notes */
      notes?: string[];
    };
    /** ChatRequest */
    ChatRequest: {
      /** Message */
      message: string;
    };
    /**
     * CompleteTaskRequest
     * @description Request body for completing a delivery task.
     */
    CompleteTaskRequest: {
      /** Summary */
      summary: string;
      /**
       * Output Artifact Ids
       * @default []
       */
      output_artifact_ids?: string[];
      /**
       * Changed Files
       * @default []
       */
      changed_files?: string[];
      /**
       * Tests Or Checks
       * @default []
       */
      tests_or_checks?: string[];
      /**
       * Follow Up Notes
       * @default []
       */
      follow_up_notes?: string[];
      /**
       * Dependency Context Used
       * @default []
       */
      dependency_context_used?: string[];
      /**
       * Decision Context Used
       * @default []
       */
      decision_context_used?: string[];
      /**
       * Context Warnings
       * @default []
       */
      context_warnings?: string[];
    };
    /**
     * CreateBugRequest
     * @description Request model for creating a bug.
     */
    CreateBugRequest: {
      /** Requirement Id */
      requirement_id: string;
      /** Title */
      title: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "low" | "medium" | "high" | "critical";
      /**
       * Owner
       * @default qa_agent
       */
      owner?: string;
    };
    /**
     * CreateRequirementRequest
     * @description Request model for creating a requirement.
     */
    CreateRequirementRequest: {
      /** Title */
      title: string;
      /**
       * Priority
       * @default medium
       * @enum {string}
       */
      priority?: "low" | "medium" | "high";
    };
    /** DesignDoc */
    DesignDoc: {
      /** Id */
      id: string;
      /** Requirement Id */
      requirement_id: string;
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /** Core Rules */
      core_rules?: string[];
      /** Acceptance Criteria */
      acceptance_criteria?: string[];
      /** Open Questions */
      open_questions?: string[];
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status?: "draft" | "pending_user_review" | "approved" | "sent_back";
      /** Sent Back Reason */
      sent_back_reason?: string | null;
    };
    /**
     * GeneratePlanRequest
     * @description Request body for generating a delivery plan.
     */
    GeneratePlanRequest: {
      /** Project Id */
      project_id: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    JsonValue: unknown;
    /** KickoffRequest */
    KickoffRequest: {
      /** Session Id */
      session_id: string;
    };
    /** MeetingMinutes */
    MeetingMinutes: {
      /** Id */
      id: string;
      /** Requirement Id */
      requirement_id: string;
      /** Title */
      title: string;
      /** Agenda */
      agenda?: string[];
      /** Attendees */
      attendees?: string[];
      /** Opinions */
      opinions?: components["schemas"]["AgentOpinion"][];
      /** Consensus Points */
      consensus_points?: string[];
      /** Conflict Points */
      conflict_points?: string[];
      /** Supplementary */
      supplementary?: {
        [key: string]: string;
      };
      /** Decisions */
      decisions?: string[];
      /** Action Items */
      action_items?: string[];
      /** Pending User Decisions */
      pending_user_decisions?: string[];
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status?: "draft" | "completed";
    };
    /** MeetingTranscript */
    MeetingTranscript: {
      /** Id */
      id: string;
      /** Meeting Id */
      meeting_id: string;
      /** Requirement Id */
      requirement_id: string;
      /** Project Id */
      project_id?: string | null;
      /** Events */
      events?: components["schemas"]["MeetingTranscriptEvent"][];
    };
    /** MeetingTranscriptEvent */
    MeetingTranscriptEvent: {
      /** Sequence */
      sequence: number;
      /** Agent Role */
      agent_role: string;
      /** Node Name */
      node_name: string;
      /**
       * Kind
       * @default llm
       * @constant
       */
      kind?: "llm";
      /** Message */
      message: string;
      /** Prompt */
      prompt?: string | null;
      /** Context */
      context?: {
        [key: string]: unknown;
      };
      /** Reply */
      reply?: unknown;
    };
    /** RequirementCard */
    RequirementCard: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /**
       * Kind
       * @default product_mvp
       * @enum {string}
       */
      kind?: "product_mvp" | "change_request";
      /**
       * Type
       * @default requirement
       * @constant
       */
      type?: "requirement";
      /**
       * Priority
       * @default medium
       * @enum {string}
       */
      priority?: "low" | "medium" | "high";
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status?: "draft" | "designing" | "pending_user_review" | "approved" | "implementing" | "self_test_passed" | "testing" | "pending_user_acceptance" | "quality_check" | "done";
      /**
       * Owner
       * @default design_agent
       */
      owner?: string;
      /** Design Doc Id */
      design_doc_id?: string | null;
      /** Balance Table Ids */
      balance_table_ids?: string[];
      /** Bug Ids */
      bug_ids?: string[];
      /** Notes */
      notes?: string[];
      /** Created At */
      created_at?: string;
    };
    /**
     * ResolveGateRequest
     * @description Request body for resolving a decision gate.
     */
    ResolveGateRequest: {
      /** Resolutions */
      resolutions: {
        [key: string]: string;
      };
    };
    /** SendMessageRequest */
    SendMessageRequest: {
      /** Message */
      message: string;
      /** Session Id */
      session_id: string;
    };
    /**
     * StartTaskRequest
     * @description Request body for starting a delivery task.
     */
    StartTaskRequest: Record<string, never>;
    /**
     * TransitionBugRequest
     * @description Request model for transitioning a bug status.
     */
    TransitionBugRequest: {
      /**
       * Next Status
       * @enum {string}
       */
      next_status: "new" | "fixing" | "fixed" | "verifying" | "closed" | "reopened" | "needs_user_decision";
    };
    /**
     * TransitionRequirementRequest
     * @description Request model for transitioning a requirement status.
     */
    TransitionRequirementRequest: {
      /**
       * Next Status
       * @enum {string}
       */
      next_status: "draft" | "designing" | "pending_user_review" | "approved" | "implementing" | "self_test_passed" | "testing" | "pending_user_acceptance" | "quality_check" | "done";
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /**
   * List Requirements
   * @description List all requirements in the workspace.
   */
  list_requirements_api_requirements_get: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RequirementCard"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Requirement
   * @description Create a new requirement.
   */
  create_requirement_api_requirements_post: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRequirementRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RequirementCard"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Requirement
   * @description Get a specific requirement by ID.
   */
  get_requirement_api_requirements__req_id__get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        req_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RequirementCard"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Transition Requirement Status
   * @description Transition a requirement to a new status.
   */
  transition_requirement_status_api_requirements__req_id__transition_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        req_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransitionRequirementRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RequirementCard"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Requirement Delivery Summary
   * @description Get aggregated delivery progress for a requirement.
   */
  get_requirement_delivery_summary_api_requirements__req_id__delivery_summary_get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        req_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Design Docs
   * @description List all design docs in the workspace.
   */
  list_design_docs_api_design_docs_get: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DesignDoc"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Design Doc
   * @description Get a specific design doc by ID.
   */
  get_design_doc_api_design_docs__design_id__get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        design_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DesignDoc"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Design Doc
   * @description Update a design doc.
   */
  update_design_doc_api_design_docs__design_id__patch: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        design_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Body_update_design_doc_api_design_docs__design_id__patch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DesignDoc"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Approve Design
   * @description Approve a design doc and transition the linked requirement.
   */
  approve_design_api_design_docs__design_id__approve_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        design_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Send Back Design
   * @description Send back a design doc for revision.
   */
  send_back_design_api_design_docs__design_id__send_back_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        design_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_send_back_design_api_design_docs__design_id__send_back_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Balance Tables
   * @description List all balance tables.
   */
  list_balance_tables_api_balance_tables_get: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BalanceTable"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Balance Table
   * @description Create a new balance table.
   */
  create_balance_table_api_balance_tables_post: {
    parameters: {
      query: {
        workspace: string;
        requirement_id: string;
        table_name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BalanceTable"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Balance Table
   * @description Get a specific balance table.
   */
  get_balance_table_api_balance_tables__table_id__get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        table_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BalanceTable"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Balance Table
   * @description Update a balance table.
   */
  update_balance_table_api_balance_tables__table_id__patch: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        table_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BalanceTableUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BalanceTable"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Bugs
   * @description List all bugs in the workspace.
   */
  list_bugs_api_bugs_get: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BugCard"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Bug
   * @description Create a new bug.
   */
  create_bug_api_bugs_post: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBugRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BugCard"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Bug
   * @description Get a specific bug by ID.
   */
  get_bug_api_bugs__bug_id__get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        bug_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BugCard"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Transition Bug Status
   * @description Transition a bug to a new status.
   */
  transition_bug_status_api_bugs__bug_id__transition_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        bug_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransitionBugRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BugCard"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Logs
   * @description List action logs, most recent first.
   */
  list_logs_api_logs_get: {
    parameters: {
      query: {
        workspace: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ActionLog"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Run Design Workflow
   * @description Run the design workflow for a requirement.
   */
  run_design_workflow_api_workflows_run_design_post: {
    parameters: {
      query: {
        workspace: string;
        requirement_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Run Dev Workflow
   * @description Run the dev workflow for a requirement.
   */
  run_dev_workflow_api_workflows_run_dev_post: {
    parameters: {
      query: {
        workspace: string;
        requirement_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Run Qa Workflow
   * @description Run the QA workflow for a requirement.
   */
  run_qa_workflow_api_workflows_run_qa_post: {
    parameters: {
      query: {
        workspace: string;
        requirement_id: string;
        fail?: boolean;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Pool Status
   * @description Return current agent thread pool status.
   */
  get_pool_status_api_pool_status_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** List Meetings */
  list_meetings_api_meetings_get: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MeetingMinutes"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Meeting */
  get_meeting_api_meetings__meeting_id__get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MeetingMinutes"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Meeting Transcript */
  get_meeting_transcript_api_meetings__meeting_id__transcript_get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MeetingTranscript"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Delivery Plan
   * @description Generate a delivery plan from a completed meeting.
   */
  generate_delivery_plan_api_meetings__meeting_id__delivery_plan_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        meeting_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeneratePlanRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Delivery Board
   * @description List all delivery board items (plans, tasks, decision gates).
   */
  list_delivery_board_api_delivery_board_get: {
    parameters: {
      query: {
        workspace: string;
        requirement_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Resolve Decision Gate
   * @description Resolve a kickoff decision gate.
   */
  resolve_decision_gate_api_kickoff_decision_gates__gate_id__resolve_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        gate_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveGateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Start Delivery Task
   * @description Start a delivery task.
   */
  start_delivery_task_api_delivery_tasks__task_id__start_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        task_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartTaskRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Retry Delivery Task
   * @description Reset a failed delivery task so the delivery runner can execute it again.
   */
  retry_delivery_task_api_delivery_tasks__task_id__retry_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Complete Delivery Task
   * @description Complete a delivery task, persisting execution results and releasing the lease.
   */
  complete_delivery_task_api_delivery_tasks__task_id__complete_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        task_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompleteTaskRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Delivery Task Events
   * @description Return chronological task events for a delivery task.
   */
  get_delivery_task_events_api_delivery_tasks__task_id__events_get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Delivery Task Session
   * @description Return Claude session messages attached to a delivery task.
   */
  get_delivery_task_session_api_delivery_tasks__task_id__session_get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Session State */
  get_session_state_api_clarifications_requirements__req_id__session_get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        req_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Start Or Get Session */
  start_or_get_session_api_clarifications_requirements__req_id__session_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        req_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Send Message */
  send_message_api_clarifications_requirements__req_id__messages_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        req_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendMessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Start Kickoff */
  start_kickoff_api_clarifications_requirements__req_id__kickoff_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        req_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KickoffRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Kickoff Task */
  get_kickoff_task_api_clarifications_kickoff_tasks__task_id__get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Sessions
   * @description List all agent sessions for a project.
   */
  list_sessions_api_sessions_project__project_id__get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List All Sessions
   * @description List all agent sessions across projects.
   */
  list_all_sessions_api_sessions_get: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Session Status
   * @description Get session status including whether the agent is busy (lease held).
   */
  get_session_status_api_sessions__session_composite_id__status_get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        session_composite_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Chat With Agent
   * @description Send a message to an idle agent and get a response.
   */
  chat_with_agent_api_agents__project_id___agent__chat_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        project_id: string;
        agent: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Agent Messages
   * @description Load chat history for an agent session from the Claude CLI transcript.
   */
  get_agent_messages_api_agents__project_id___agent__messages_get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        project_id: string;
        agent: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
