/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    /** Health */
    get: operations["health_api_health_get"];
  };
  "/api/requirements": {
    /**
     * List Requirements
     * @description List all requirements in the workspace.
     */
    get: operations["list_requirements_api_requirements_get"];
    /**
     * Create Requirement
     * @description Create a new requirement.
     */
    post: operations["create_requirement_api_requirements_post"];
  };
  "/api/requirements/{req_id}": {
    /**
     * Get Requirement
     * @description Get a specific requirement by ID.
     */
    get: operations["get_requirement_api_requirements__req_id__get"];
  };
  "/api/requirements/{req_id}/transition": {
    /**
     * Transition Requirement Status
     * @description Transition a requirement to a new status.
     */
    post: operations["transition_requirement_status_api_requirements__req_id__transition_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * CreateRequirementRequest
     * @description Request model for creating a requirement.
     */
    CreateRequirementRequest: {
      /** Title */
      title: string;
      /**
       * Priority
       * @default medium
       */
      priority?: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** RequirementCard */
    RequirementCard: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /**
       * Type
       * @default requirement
       * @constant
       */
      type?: "requirement";
      /**
       * Priority
       * @default medium
       * @enum {string}
       */
      priority?: "low" | "medium" | "high";
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status?: "draft" | "designing" | "pending_user_review" | "approved" | "implementing" | "self_test_passed" | "testing" | "pending_user_acceptance" | "quality_check" | "done";
      /**
       * Owner
       * @default design_agent
       */
      owner?: string;
      /** Design Doc Id */
      design_doc_id?: string | null;
      /** Balance Table Ids */
      balance_table_ids?: string[];
      /** Bug Ids */
      bug_ids?: string[];
      /** Notes */
      notes?: string[];
    };
    /**
     * TransitionRequirementRequest
     * @description Request model for transitioning a requirement status.
     */
    TransitionRequirementRequest: {
      /**
       * Next Status
       * @enum {string}
       */
      next_status: "draft" | "designing" | "pending_user_review" | "approved" | "implementing" | "self_test_passed" | "testing" | "pending_user_acceptance" | "quality_check" | "done";
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** BugCard */
    BugCard: {
      /** Id */
      id: string;
      /** Requirement Id */
      requirement_id: string;
      /** Title */
      title: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "low" | "medium" | "high" | "critical";
      /**
       * Status
       * @default new
       * @enum {string}
       */
      status: "new" | "fixing" | "fixed" | "verifying" | "closed" | "reopened" | "needs_user_decision";
      /**
       * Reopen Count
       * @default 0
       */
      reopen_count: number;
      /** Owner */
      owner: string;
      /** Repro Steps */
      repro_steps?: string[];
      /** Notes */
      notes?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /**
   * List Requirements
   * @description List all requirements in the workspace.
   */
  list_requirements_api_requirements_get: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RequirementCard"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Requirement
   * @description Create a new requirement.
   */
  create_requirement_api_requirements_post: {
    parameters: {
      query: {
        workspace: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRequirementRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RequirementCard"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Requirement
   * @description Get a specific requirement by ID.
   */
  get_requirement_api_requirements__req_id__get: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        req_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RequirementCard"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Transition Requirement Status
   * @description Transition a requirement to a new status.
   */
  transition_requirement_status_api_requirements__req_id__transition_post: {
    parameters: {
      query: {
        workspace: string;
      };
      path: {
        req_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransitionRequirementRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RequirementCard"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
