from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, HTTPException

from studio.domain.requirement_flow import transition_requirement
from studio.schemas.design_doc import DesignDoc
from studio.schemas.requirement import RequirementCard
from studio.storage.workspace import StudioWorkspace

router = APIRouter(prefix="/workflows", tags=["workflows"])


def _get_workspace(workspace: str) -> StudioWorkspace:
    """Get workspace instance."""
    workspace_path = Path(workspace) / ".studio-data"
    return StudioWorkspace(workspace_path)


@router.post("/run-design")
async def run_design_workflow(
    workspace: str,
    requirement_id: str,
) -> dict[str, object]:
    """Run the design workflow for a requirement."""
    store = _get_workspace(workspace)
    requirement = store.requirements.get(requirement_id)

    # Transition through design states
    designing = transition_requirement(requirement, "designing")
    pending_review = transition_requirement(designing, "pending_user_review")

    # Create design doc
    design_doc = DesignDoc(
        id=f"design_{requirement.id.split('_')[-1]}",
        requirement_id=requirement.id,
        title=f"{requirement.title} Design",
        summary=requirement.title,
        core_rules=["rule 1"],
        acceptance_criteria=["criterion 1"],
        open_questions=["question 1"],
        status="pending_user_review",
    )

    # Update requirement with design doc link
    updated_req = pending_review.model_copy(update={"design_doc_id": design_doc.id})

    store.design_docs.save(design_doc)
    store.requirements.save(updated_req)

    return {
        "requirement_id": updated_req.id,
        "requirement_status": updated_req.status,
        "design_doc_id": design_doc.id,
        "design_doc_status": design_doc.status,
    }


@router.post("/run-dev")
async def run_dev_workflow(
    workspace: str,
    requirement_id: str,
) -> dict[str, object]:
    """Run the dev workflow for a requirement."""
    store = _get_workspace(workspace)
    requirement = store.requirements.get(requirement_id)

    # Validate ready for dev
    from studio.domain.services import validate_requirement_ready_for_dev

    design_doc = store.design_docs.get(requirement.design_doc_id or "")
    balance_tables = [
        store.balance_tables.get(bt_id)
        for bt_id in requirement.balance_table_ids
    ]

    try:
        validate_requirement_ready_for_dev(requirement, design_doc, balance_tables)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    # Transition to implementing
    implementing = transition_requirement(requirement, "implementing")
    self_test_passed = transition_requirement(implementing, "self_test_passed")

    updated = store.requirements.save(self_test_passed)

    return {
        "requirement_id": updated.id,
        "status": updated.status,
    }


@router.post("/run-qa")
async def run_qa_workflow(
    workspace: str,
    requirement_id: str,
    fail: bool = False,
) -> dict[str, object]:
    """Run the QA workflow for a requirement."""
    store = _get_workspace(workspace)
    requirement = store.requirements.get(requirement_id)

    # Transition to testing
    testing = transition_requirement(requirement, "testing")

    if not fail:
        # Pass and go to user acceptance
        accepted = transition_requirement(testing, "pending_user_acceptance")
        updated = store.requirements.save(accepted)
        return {
            "requirement_id": updated.id,
            "status": updated.status,
        }

    # Fail: create bug and go back to implementing
    from uuid import uuid4

    implementing = transition_requirement(testing, "implementing")
    bug_id = f"bug_{uuid4().hex[:8]}"

    from studio.schemas.bug import BugCard

    bug = BugCard(
        id=bug_id,
        requirement_id=requirement_id,
        title=f"QA failure for {requirement_id}",
        severity="high",
        owner="qa_agent",
        repro_steps=["Generated by QA"],
    )

    updated_req = implementing.model_copy(
        update={"bug_ids": [*implementing.bug_ids, bug_id]}
    )

    store.bugs.save(bug)
    store.requirements.save(updated_req)

    return {
        "requirement_id": updated_req.id,
        "status": updated_req.status,
        "bug_id": bug_id,
    }
